//This file is generated by tools!
//Please do not modify this file!
public class DataDefine {

	public const int Units_Unit_ID = 0;
	public const int Units_Unit_Type = 1;
	public const int Units_Unit_AiType = 2;
	public const int Units_Unit_DamageOpenFog = 3;
	public const int Units_Unit_PickTargetType = 4;
	public const int Units_Unit_UnitType = 5;
	public const int Units_Unit_TriggerMine = 6;
	public const int Units_Unit_SightRange = 7;
	public const int Units_Unit_AttackRange = 8;
	public const int Units_Unit_AttackActionTime = 9;
	public const int Units_Unit_AttackInterval = 10;
	public const int Units_Unit_TargetType = 11;
	public const int Units_Unit_PreferTarget = 12;
	public const int Units_Unit_DamageType = 13;
	public const int Units_Unit_DamagePower = 14;
	public const int Units_Unit_DamageRange = 15;
	public const int Units_Unit_Speed = 16;
	public const int Units_Unit_HP = 17;
	public const int Units_Unit_PhyDamage = 18;
	public const int Units_Unit_PowerDamage = 19;
	public const int Units_Unit_Remedy = 20;
	public const int Units_Unit_Dps = 21;
	public const int Units_Unit_PhyShield = 22;
	public const int Units_Unit_PowerShield = 23;
	public const int Units_Unit_DeploySound = 24;
	public const int Units_Unit_DescZ = 25;
	public const int Units_Unit_Desc = 26;

}